import type { BlockInstance } from "@/lib/builder/schema";

const escapeHtml = (value: string) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const renderBlock = (block: BlockInstance): string => {
  const props = block.props as Record<string, unknown>;

  switch (block.type) {
    case "heading": {
      const tag = typeof props.tag === "string" ? props.tag : "h2";
      const text = typeof props.text === "string" ? props.text : "Your heading";
      return `<${tag} class="spb-heading">${escapeHtml(text)}</${tag}>`;
    }
    case "text": {
      const text = typeof props.text === "string" ? props.text : "Add supporting copy";
      return `<p class="spb-text">${escapeHtml(text)}</p>`;
    }
    case "button": {
      const label = typeof props.label === "string" ? props.label : "Learn more";
      const href = typeof props.href === "string" && props.href.length > 0 ? props.href : "#";
      const variant = typeof props.variant === "string" ? props.variant : "primary";
      const classes = variant === "ghost" ? "spb-button spb-button--ghost" : "spb-button";
      return `<a href="${escapeHtml(href)}" class="${classes}">${escapeHtml(label)}</a>`;
    }
    case "image": {
      const src = typeof props.src === "string" ? props.src : "";
      const alt = typeof props.alt === "string" ? props.alt : "";
      if (!src) {
        return "";
      }
      return `<div class="spb-image"><img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}" loading="lazy" /></div>`;
    }
    case "code": {
      const code = typeof props.code === "string" ? props.code : "";
      return code;
    }
    case "section": {
      const title = typeof props.title === "string" ? props.title : "Section title";
      const text = typeof props.text === "string" ? props.text : "Add copy";
      return `
<section class="spb-section">
  <div class="spb-section__inner">
    <h2 class="spb-section__title">${escapeHtml(title)}</h2>
    <p class="spb-section__text">${escapeHtml(text)}</p>
  </div>
</section>
`.trim();
    }
    default:
      return "";
  }
};

const SECTION_STYLES = `
.spb-section { padding: 80px 20px; background: #0b1220; color: #f1f5f9; }
.spb-section__inner { max-width: 960px; margin: 0 auto; text-align: center; }
.spb-section__title { font-size: clamp(32px, 4vw, 48px); margin-bottom: 16px; }
.spb-section__text { font-size: 18px; line-height: 1.6; color: #cbd5f5; }
.spb-heading { font-size: clamp(28px, 3.5vw, 42px); font-weight: 600; margin: 24px 0 12px; }
.spb-text { font-size: 18px; line-height: 1.7; margin-bottom: 18px; color: #cbd5f5; }
.spb-button { display: inline-flex; align-items: center; gap: 8px; background: #4f46e5; color: #fff; padding: 12px 28px; border-radius: 9999px; text-decoration: none; font-weight: 500; transition: background 0.2s ease; }
.spb-button:hover { background: #4338ca; }
.spb-button--ghost { background: transparent; border: 1px solid rgba(255,255,255,0.35); }
.spb-button--ghost:hover { background: rgba(255,255,255,0.08); }
.spb-image { margin: 32px auto; max-width: 680px; border-radius: 24px; overflow: hidden; box-shadow: 0 30px 60px rgba(15,23,42,0.3); }
`; // NOSONAR

export const generateSectionAssets = (pageId: string, blocks: BlockInstance[]) => {
  const bodyHtml = blocks.map(renderBlock).filter(Boolean).join("\n\n");

  const sectionLiquid = `
<!-- Generated by Space Page Builder -->
<style>
${SECTION_STYLES}
</style>
<div class="space-page-builder">
${bodyHtml}
</div>
{% schema %}
{
  "name": "Space page builder",
  "settings": [],
  "presets": [
    {
      "name": "Space page"
    }
  ]
}
{% endschema %}
`.trim();

  const template = {
    sections: {
      main: {
        type: `pagebuilder-${pageId}`,
        settings: {},
      },
    },
    order: ["main"],
  } satisfies Record<string, unknown>;

  const templateJson = JSON.stringify(template, null, 2);

  return {
    sectionLiquid,
    templateJson,
    sectionKey: `sections/pagebuilder-${pageId}.liquid`,
    templateKey: `templates/page.pagebuilder-${pageId}.json`,
  };
};
